services:
    sherlockode_afb.file_upload.controller:
        class: Sherlockode\AdvancedFormBundle\Controller\FileUploadController
        arguments:
            - '@sherlockode_afb.upload_manager'
            - '@sherlockode_afb.mapping_manager'
            - '%sherlockode_afb.tmp_uploaded_file_class%'
