services:
    sherlockode_afb.file.form_type:
        class: Sherlockode\AdvancedFormBundle\Form\Type\FileType
        arguments:
            - '@router'
            - '@sherlockode_afb.annotation_manager'
            - '@sherlockode_afb.mapping_manager'
            - '%sherlockode_afb.tmp_uploaded_file_dir%'
        tags: ['form.type']
