services:
    sherlockode_afb.file.form_entity_type:
        class: Sherlockode\AdvancedFormBundle\Form\Type\EntityMappingType
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@sherlockode_afb.mapping_manager'
        tags: ['form.type']
    sherlockode_afb.file.form_type:
        class: Sherlockode\AdvancedFormBundle\Form\Type\FileType
        arguments:
            - '@router'
            - '@sherlockode_afb.upload_manager'
            - '@sherlockode_afb.mapping_manager'
            - '%sherlockode_afb.tmp_uploaded_file_dir%'
        tags: ['form.type']
    sherlockode_afb.file.collection_type:
        class: Sherlockode\AdvancedFormBundle\Form\Type\FileCollectionType
        tags: ['form.type']
    sherlockode_afb.file.tmp_type:
        class: Sherlockode\AdvancedFormBundle\Form\Type\TemporaryUploadedFileType
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%sherlockode_afb.tmp_uploaded_file_class%'
        tags: ['form.type']
    sherlockode_afb.file.upload_type:
        class: Sherlockode\AdvancedFormBundle\Form\Type\UploadFileType
        arguments:
            - '@sherlockode_afb.mapping_manager'
            - '@translator'
        tags: ['form.type']
    sherlockode_afb.form.dependent_entity_type:
        class: Sherlockode\AdvancedFormBundle\Form\Type\DependentEntityType
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@translator'
        tags: ['form.type']
