services:
    _defaults:
        autowire: true

    Sherlockode\AdvancedFormBundle\Manager\:
        resource: '../../Manager'
        public: true

    sherlockode_afb.upload_handler.vich:
        class: Sherlockode\AdvancedFormBundle\UploadHandler\VichUploadHandler

    Sherlockode\AdvancedFormBundle\Manager\UploadManager:
        arguments:
            $tmpStorage: '@sherlockode_afb.storage.tmp_storage'
        calls:
            - [ addHandler, ['@sherlockode_afb.upload_handler.vich']]

    Sherlockode\AdvancedFormBundle\Manager\MappingManager:
        calls:
            - [setMapping, ['%sherlockode_afb.uploader_mappings%']]

    sherlockode_afb.twig_extension:
        class: Sherlockode\AdvancedFormBundle\Twig\Extension\UploaderExtension
        tags:
            - { name: twig.extension }
