services:
    _defaults:
        autowire: true

    sherlockode_afb.upload_handler.vich:
        class: Sherlockode\AdvancedFormBundle\UploadHandler\VichUploadHandler

    sherlockode_afb.upload_handler.property:
        class: Sherlockode\AdvancedFormBundle\UploadHandler\PropertyUploadHandler
        arguments:
            - '@sherlockode_afb.mapping_manager'
            - ~

    sherlockode_afb.upload_manager:
        class: Sherlockode\AdvancedFormBundle\Manager\UploadManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@sherlockode_afb.mapping_manager'
            - '@sherlockode_afb.storage.tmp_storage'
            - '%sherlockode_afb.tmp_uploaded_file_class%'
        calls:
            - [ addHandler, ['@sherlockode_afb.upload_handler.vich']]
            - [ addHandler, ['@sherlockode_afb.upload_handler.property']]

    sherlockode_afb.annotation_manager:
        class: Sherlockode\AdvancedFormBundle\Manager\AnnotationManager

    sherlockode_afb.mapping_manager:
        class: Sherlockode\AdvancedFormBundle\Manager\MappingManager
        calls:
            - [setMapping, ['%sherlockode_afb.uploader_mappings%']]

    sherlockode_afb.storage.tmp_storage:
        class: Sherlockode\AdvancedFormBundle\Storage\FilesystemStorage
        arguments:
            - '%sherlockode_afb.tmp_uploaded_file_dir%'

    sherlockode_afb.twig_extension:
        class: Sherlockode\AdvancedFormBundle\Twig\Extension\UploaderExtension
        arguments:
            - '@router'
            - '@sherlockode_afb.mapping_manager'
        tags:
            - { name: twig.extension }
