services:
    _defaults:
        autowire: true

    Sherlockode\AdvancedFormBundle\Manager\:
        resource: '../../Manager'
        public: true

    Sherlockode\AdvancedFormBundle\Manager\MappingManager:
        calls:
            - [setMapping, ['%sherlockode_afb.uploader_mappings%']]

    sherlockode_afb.twig_extension:
        class: Sherlockode\AdvancedFormBundle\Twig\Extension\UploaderExtension
        tags:
            - { name: twig.extension }
