services:
    sherlockode_afb.upload_handler.vich:
        class: Sherlockode\AdvancedFormBundle\UploadHandler\VichUploadHandler
        arguments:
            - '@vich_uploader.upload_handler'
            - '@annotation_reader'
        tags:
            - { name: 'sherlockode_afb.upload_handler', alias: vich }

    sherlockode_afb.upload_handler.property:
        class: Sherlockode\AdvancedFormBundle\UploadHandler\PropertyUploadHandler
        arguments:
            - '@sherlockode_afb.mapping_manager'
            - ~
        tags:
            - { name: 'sherlockode_afb.upload_handler', alias: property }

    sherlockode_afb.upload_manager:
        class: Sherlockode\AdvancedFormBundle\Manager\UploadManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@sherlockode_afb.storage.tmp_storage'
            - '%sherlockode_afb.tmp_uploaded_file_class%'

    sherlockode_afb.mapping_manager:
        class: Sherlockode\AdvancedFormBundle\Manager\MappingManager
        calls:
            - [setMappingData, ['%sherlockode_afb.uploader_mappings%']]

    sherlockode_afb.storage.tmp_storage:
        class: Sherlockode\AdvancedFormBundle\Storage\FilesystemStorage
        arguments:
            - '%sherlockode_afb.tmp_uploaded_file_dir%'

    sherlockode_afb.twig_extension:
        class: Sherlockode\AdvancedFormBundle\Twig\Extension\UploaderExtension
        arguments:
            - '@router'
            - '@sherlockode_afb.mapping_manager'
            - '@sherlockode_afb.upload_manager'
        tags:
            - { name: twig.extension }

    sherlockode_afb.dependent_entity.mapper_pool:
        class: Sherlockode\AdvancedFormBundle\DependentEntity\DependentMapperPool
