sherlockode_afb_upload:
    path: /sherlockodeadvancedform/upload
    defaults: { _controller: sherlockode_afb.file_upload.controller:uploadFileAction }

sherlockode_afb_remove:
    path: /sherlockodeadvancedform/remove
    defaults: { _controller: sherlockode_afb.file_upload.controller:removeFileAction }

sherlockode_afb_upload_tmp:
    path: /sherlockodeadvancedform/upload_tmp
    defaults: { _controller: sherlockode_afb.file_upload.controller:uploadTmpAction }

sherlockode_afb_remove_tmp:
    path: /sherlockodeadvancedform/remove_tmp
    defaults: { _controller: sherlockode_afb.file_upload.controller:removeTmpFileAction }

sherlockode_afb_preview:
    path: /sherlockodeadvancedform/uploaded/{token}
    defaults: { _controller: sherlockode_afb.file_upload.controller:viewUploadedFileAction }
